function Add_Object_Callback(~, ~, ~)

global OBJECTS
global AX
global r1 r2 r3 r4
global e1 e2 e3 e4 e5 e6 e7 e8 e9 sl
global sl1 sl2 sl3 sl4 sl5 sl6 sl7 sl8 sl9
global Xpts Ypts Zpts X0pts Y0pts Z0pts X1pts Y1pts Z1pts HU

[Xpts, Ypts, Zpts, X0pts, Y0pts, Z0pts, X1pts, Y1pts, Z1pts, HU] = deal([]);

NEW_OBJ_ID = 1;

fh = figure('Position',[1 300 900 525],'Name','Object Selection','Resize','On');

bg = uibuttongroup('Visible','off',...
                  'Position',[0.04 0.75 0.53 0.20],...
                  'SelectionChangedFcn',@bselection);
              
AX = axes('Position',[0.64,0.3,0.31,0.5]);
set(AX,'Box','on')
view(AX,[45,27])
% xlim(AX,[-100,100])
% ylim(AX,[-100,100])
% zlim(AX,[-100,100])
set(AX,'DataAspectRatio',[1 1 1])
set(AX,'Color',[0.95,0.92,0.9])
xlabel(AX,'LR')
ylabel(AX,'SI')
zlabel(AX,'AP')
              
r1 = uicontrol(bg,'Style',...
                  'radiobutton',...
                  'String','Sphere',...
                  'Units','normalized',...
                  'FontSize',12,...
                  'Position',[0.15 0.65 0.5 0.2],...
                  'HandleVisibility','off');
              
r2 = uicontrol(bg,'Style','radiobutton',...
                  'String','Cylinder',...
                  'Units','normalized',...
                  'FontSize',12,...
                  'Position',[0.15 0.25 0.5 0.2],...
                  'HandleVisibility','off');

r3 = uicontrol(bg,'Style','radiobutton',...
                  'String','Box',...
                  'Units','normalized',...
                  'FontSize',12,...
                  'Position',[0.55 0.65 0.5 0.2],...
                  'HandleVisibility','off');
              
r4 = uicontrol(bg,'Style','radiobutton',...
                  'String','Custom Shape',...
                  'Units','normalized',...
                  'FontSize',12,...
                  'Position',[0.55 0.25 0.5 0.2],...
                  'HandleVisibility','off');
              
% Make the uibuttongroup visible after creating child objects. 
bg.Visible = 'on';

x = [0.04, 0.20, 0.29, 0.49];
y = [0.65, 0.57, 0.49, 0.35, 0.27, 0.19];
w = [0.16, 0.06, 0.20, 0.06];
h = 0.047;

fsize = 9;

t1 = uicontrol('Parent',fh,'Style','text',...
                  'String','Sup-Inf Position [cm] = ',...
                  'Units','normalized',...
                  'FontSize',fsize,...
                  'Position',[x(1) y(1) w(1) h],...
                  'HorizontalAlignment','right');
e1 = uicontrol('Parent',fh,'Style','edit',...
                  'String','0',...
                  'Units','normalized',...
                  'FontSize',fsize,...
                  'Position',[x(2) y(1)+0.007 w(2) h],...
                  'CallBack',@Constr_Numeric1);


              
t2 = uicontrol('Parent',fh,'Style','text',...
                  'String','Right-Left Position [cm] = ',...
                  'Units','normalized',...
                  'FontSize',fsize,...
                  'Position',[x(1) y(2) w(1) h],...
                  'HorizontalAlignment','right');
e2 = uicontrol('Parent',fh,'Style','edit',...
                  'String','0',...
                  'Units','normalized',...
                  'FontSize',fsize,...
                  'Position',[x(2) y(2)+0.007 w(2) h],...
                  'CallBack',@Constr_Numeric1);
              
              
t3 = uicontrol('Parent',fh,'Style','text',...
                  'String','Ant-Post Position [cm] = ',...
                  'Units','normalized',...
                  'FontSize',fsize,...
                  'Position',[x(1) y(3) w(1) h],...
                  'HorizontalAlignment','right');
e3 = uicontrol('Parent',fh,'Style','edit',...
                  'String','0',...
                  'Units','normalized',...
                  'FontSize',fsize,...
                  'Position',[x(2) y(3)+0.007 w(2) h],...
                  'CallBack',@Constr_Numeric1);
              
              
t4 = uicontrol('Parent',fh,'Style','text',...
                  'String','Ant-Post Axis Rotation [deg] = ',...
                  'Units','normalized',...
                  'FontSize',fsize,...
                  'Position',[x(3) y(1) w(3) h],...
                  'HorizontalAlignment','right',...
                  'Enable','off');
e4 = uicontrol('Parent',fh,'Style','edit',...
                  'String','0',...
                  'Units','normalized',...
                  'FontSize',fsize,...
                  'Position',[x(4) y(1)+0.007 w(4) h],...
                  'CallBack',@Constr_Numeric2,...
                  'Enable','off');
              
              
t5 = uicontrol('Parent',fh,'Style','text',...
                  'String','Sup-Inf Axis Rotation [deg] = ',...
                  'Units','normalized',...
                  'FontSize',fsize,...
                  'Position',[x(3) y(2) w(3) h],...
                  'HorizontalAlignment','right',...
                  'Enable','off');
e5 = uicontrol('Parent',fh,'Style','edit',...
                  'String','0',...
                  'Units','normalized',...
                  'FontSize',fsize,...
                  'Position',[x(4) y(2)+0.007 w(4) h],...
                  'CallBack',@Constr_Numeric2,...
                  'Enable','off');

              
t6 = uicontrol('Parent',fh,'Style','text',...
                  'String','Axial Rotation [deg] = ',...
                  'Units','normalized',...
                  'FontSize',fsize,...
                  'Position',[x(3) y(3) w(3) h],...
                  'Enable','off',...
                  'HorizontalAlignment','right');
e6 = uicontrol('Parent',fh,'Style','edit',...
                  'String','0',...
                  'Units','normalized',...
                  'FontSize',fsize,...
                  'Position',[x(4) y(3)+0.007 w(4) h],...
                  'CallBack',@Constr_Numeric2,...
                  'Enable','off');
              
% sstr = ['--------------------------------------------------------',...
%     '---------------------------------------------------------',...
%     '----------'];
% tline = uicontrol('Parent',fh,'Style','text',...
%                   'String',sstr,...
%                   'Units','normalized',...
%                   'FontSize',fsize,...
%                   'Position',[0.03 y(3)-0.07 0.55 h],...
%                   'HorizontalAlignment','center');
              
              
t7 = uicontrol('Parent',fh,'Style','text',...
                  'String','Sphere Radius [cm] = ',...
                  'Units','normalized',...
                  'FontSize',fsize,...
                  'Position',[x(1) y(4) w(1) h],...
                  'HorizontalAlignment','right');
e7 = uicontrol('Parent',fh,'Style','edit',...
                  'String','1',...
                  'Units','normalized',...
                  'FontSize',fsize,...
                  'Position',[x(2) y(4)+0.007 w(2) h],...
                  'CallBack',@Constr_Numeric3);
              
              
t8 = uicontrol('Parent',fh,'Style','text',...
                  'String','Cylinder Length [cm] = ',...
                  'Units','normalized',...
                  'FontSize',fsize,...
                  'Position',[x(1) y(5) w(1) h],...
                  'HorizontalAlignment','right',...
                  'Visible','off');
e8 = uicontrol('Parent',fh,'Style','edit',...
                  'String','1',...
                  'Units','normalized',...
                  'FontSize',fsize,...
                  'Position',[x(2) y(5)+0.007 w(2) h],...
                  'CallBack',@Constr_Numeric3,...
                  'Visible','off');
              
              
t9 = uicontrol('Parent',fh,'Style','text',...
                  'String','Box Height [cm] = ',...
                  'Units','normalized',...
                  'FontSize',fsize,...
                  'Position',[x(1) y(6) w(1) h],...
                  'HorizontalAlignment','right',...
                  'Visible','off');
e9 = uicontrol('Parent',fh,'Style','edit',...
                  'String','1',...
                  'Units','normalized',...
                  'FontSize',fsize,...
                  'Position',[x(2) y(6)+0.007 w(2) h],...
                  'CallBack',@Constr_Numeric3,...
                  'Visible','off');
              

sl = uicontrol('Parent',fh,'Style','slider',...
                  'Value',1000,...
                  'Units','normalized',...
                  'FontSize',fsize,...
                  'Position',[0.06 0.09 0.88 0.035],...
                  'Min', -1000,...
                  'Max', 4000,...
                  'SliderStep', [0.002,0.02],...
                  'Interruptible','off',...
                  'BusyAction','cancel');
              
%% Slider buttons        

shiftstep = 0.1;
rotstep = 1;
expandstep = 0.1;
              
sl1 = uicontrol('Parent',fh,'Style','slider',...
                  'Value',0,...
                  'Units','normalized',...
                  'Position',[0.26 0.657 0.02 0.047],...
                  'Min', -250,...
                  'Max', 250,...
                  'SliderStep', [1/500*shiftstep,1]);  
              
sl2 = uicontrol('Parent',fh,'Style','slider',...
                  'Value',0,...
                  'Units','normalized',...
                  'Position',[0.26 0.577 0.02 0.047],...
                  'Min', -250,...
                  'Max', 250,...
                  'SliderStep', [1/500*shiftstep,1]);   
              
sl3 = uicontrol('Parent',fh,'Style','slider',...
                  'Value',0,...
                  'Units','normalized',...
                  'Position',[0.26 0.497 0.02 0.047],...
                  'Min', -250,...
                  'Max', 250,...
                  'SliderStep', [1/500*shiftstep,1]);   

sl4 = uicontrol('Parent',fh,'Style','slider',...
                  'Value',0,...
                  'Units','normalized',...
                  'Position',[0.55 0.657 0.02 0.047],...
                  'Min', -3600,...
                  'Max', 3600,...
                  'SliderStep', [1/7200*rotstep,1]);   
      
sl5 = uicontrol('Parent',fh,'Style','slider',...
                  'Value',0,...
                  'Units','normalized',...
                  'Position',[0.55 0.577 0.02 0.047],...
                  'Min', -3600,...
                  'Max', 3600,...
                  'SliderStep', [1/7200*rotstep,1]);   
              
sl6 = uicontrol('Parent',fh,'Style','slider',...
                  'Value',0,...
                  'Units','normalized',...
                  'Position',[0.55 0.497 0.02 0.047],...
                  'Min', -3600,...
                  'Max', 3600,...
                  'SliderStep', [1/7200*rotstep,1]);   
                            
sl7 = uicontrol('Parent',fh,'Style','slider',...
                  'Value',1,...
                  'Units','normalized',...
                  'Position',[0.26 0.357 0.02 0.047],...
                  'Min', 0,...
                  'Max', 250,...
                  'SliderStep', [1/250*expandstep,1]);   
      
sl8 = uicontrol('Parent',fh,'Style','slider',...
                  'Value',1,...
                  'Units','normalized',...
                  'Position',[0.26 0.277 0.02 0.047],...
                  'Min', 0,...
                  'Max', 250,...
                  'SliderStep', [1/250*expandstep,1],...
                  'Visible','off');   
              
sl9 = uicontrol('Parent',fh,'Style','slider',...
                  'Value',1,...
                  'Units','normalized',...
                  'Position',[0.26 0.197 0.02 0.047],...
                  'Min', 0,...
                  'Max', 250,...
                  'SliderStep', [1/250*expandstep,1],...
                  'Visible','off');   
              
%%              



slb_handles = [sl1,sl2,sl3,sl4,sl5,sl6,sl7,sl8,sl9];
e_handles = [e1,e2,e3,e4,e5,e6,e7,e8,e9];
set(e_handles,'Interruptible','off','BusyAction','cancel')
set(slb_handles,'FontSize',fsize,'Interruptible','off','BusyAction','cancel');

              
sllh1 = addlistener(sl,'Value','PreSet',@Change_HU);
sllh2 = addlistener(sl,'Value','PostSet',@Change_HU);
sllh3 = addlistener(slb_handles,'Value','PostSet',@Slider_Change_Val);

              
ts = uicontrol('Parent',fh,'Style','text',...
                  'String','Hounsfield Units = 1000',...
                  'Units','normalized',...
                  'FontSize',fsize,...
                  'Position',[0.38 0.04 0.3 0.035],...
                  'HorizontalAlignment','left',...
                  'FontWeight','bold',...
                  'HandleVisibility','off');
              
              
Adjust_Shape
   
    function Change_HU(~,~)

        hu = get(sl,'Value');
        hu = 10*round(hu/10);
        set(ts,'String',['Hounsfield Units = ',num2str(hu)])
        set(sl,'Value',hu)
        
        Adjust_Shape

    end 

    function Slider_Change_Val(~,~)
        vals = zeros(1,9);
%         evals = get(e_handles,'String');
%         for n = 1:9
%             newslbval = get(slb_handles(n),'Value');
%             if abs(old_slbvals{n} - newslbval) > 1
%                 evalnum = round(str2double(evals{n}));
%                 set(slb_handles(n),'Value',evalnum + newslbval - old_slbvals{n});
%             end   
%         end
        vals_cell = get(slb_handles,'Value');
        for n = 1:9
            vals(n) = vals_cell{n};
        end
        for n = 4:6
            if vals(n) == -3600
                vals(n) = 0;
                set(slb_handles(n),'Value',vals(n));
            elseif vals(n) == 3600
                vals(n) = 0;
                set(slb_handles(n),'Value',vals(n));
            end
        end
        vals(4:6) = mod(vals(4:6),360);
        for n = 1:9
            set(e_handles(n),'String',num2str(vals(n)))
        end
        Adjust_Shape
    end

    function Edit_Value_Change(~,~)
        
        disp('hi')
        Adjust_Shape

    end 


       
   function bselection(~,callbackdata)

       if strcmp(callbackdata.NewValue.String,'Sphere')
           set([t7,e7,sl7],'Visible','on')
           set([t8,e8,t9,e9,sl8,sl9],'Visible','off')
           set(t7,'String','Sphere Radius [cm] = ')
           set([t4,e4,t5,e5,t6,e6,sl4,sl5,sl6],'Enable','off')
           NEW_OBJ_ID = 1;
       elseif strcmp(callbackdata.NewValue.String,'Cylinder')
           set([t7,e7,t8,e8,sl7,sl8],'Visible','on')
           set([t9,e9,sl9],'Visible','off')
           set(t7,'String','Cylinder Radius [cm] = ')
           set(t8,'String','Cylinder Length [cm] = ')
           set([t4,e4,t5,e5,sl4,sl5],'Enable','on')
           set([t6,e6,sl6],'Enable','off')
           NEW_OBJ_ID = 2;
       elseif strcmp(callbackdata.NewValue.String,'Box')
           set([t7,e7,t8,e8,t9,e9,sl7,sl8,sl9],'Visible','on')
           set(t7,'String','Box Length [cm] = ')
           set(t8,'String','Box Width [cm] = ')
           set(t9,'String','Box Height [cm] = ')
           set([t4,e4,t5,e5,t6,e6,sl4,sl5,sl6],'Enable','on')
           NEW_OBJ_ID = 3;
       elseif strcmp(callbackdata.NewValue.String,'Custom Shape')
           set([t7,e7,t8,e8,t9,e9,sl7,sl8,sl9],'Visible','off')
           set([t4,e4,t5,e5,t6,e6,sl4,sl5,sl6],'Enable','on')
           NEW_OBJ_ID = 4;
       end
       Adjust_Shape
   end


btn1 = uicontrol('Parent',fh,...
           'Units','normalized',...
           'Position',[0.34 0.32 0.22 0.08],...
           'String','Add Shape',...
           'FontSize',12,...
           'FontAngle','italic',...
           'Callback',@close_dlg1);
       
btn2 = uicontrol('Parent',fh,...
           'Units','normalized',...
           'Position',[0.34 0.2 0.22 0.08],...
           'String','Cancel',...
           'FontSize',12,...
           'FontAngle','italic',...
           'Callback',@close_dlg2);

    function close_dlg1(~,~)
        n = length(OBJECTS);
        OBJECTS(n + 1).Xpts = Xpts;
        OBJECTS(n + 1).Ypts = Ypts;
        OBJECTS(n + 1).Zpts = Zpts;
        OBJECTS(n + 1).X0pts = X0pts;
        OBJECTS(n + 1).Y0pts = Y0pts;
        OBJECTS(n + 1).Z0pts = Z0pts;
        OBJECTS(n + 1).X1pts = X1pts;
        OBJECTS(n + 1).Y1pts = Y1pts;
        OBJECTS(n + 1).Z1pts = Z1pts;
        OBJECTS(n + 1).HU = HU;
        delete(sllh1)
        delete(sllh2)
        delete(sllh3)
        delete(gcf)
    end

    function close_dlg2(~,~)
        delete(sllh1)
        delete(sllh2)
        delete(sllh3)
        delete(gcf)
    end

    function Constr_Numeric1(src,~)
        str = get(src,'String');
        if isnan(str2double(str))
            set(src,'String','0');
        elseif str2double(str) > 250
            set(src,'String','250');
        elseif str2double(str) < -250
            set(src,'String','-250');
        end
        for n = 1:3
            val = get(e_handles(n),'String');
            set(slb_handles(n),'Value',(str2double(val)))
        end
        Adjust_Shape
    end  
    function Constr_Numeric2(src,~)
        str = get(src,'String');
        if isnan(str2double(str))
            set(src,'String','0');
        elseif str2double(str) < 0
            v = str2double(str);
            v = v - 360*ceil(v/360);
            v = 360 + v;
            set(src,'String',num2str(v));
        elseif str2double(str) >= 360
            v = str2double(str);
            v = v - 360*floor(v/360);
            set(src,'String',num2str(v));
        end
        for n = 4:6
            val = get(e_handles(n),'String');
            set(slb_handles(n),'Value',(str2double(val)))
        end
        Adjust_Shape
    end
    function Constr_Numeric3(src,~)
        str = get(src,'String');
        if isnan(str2double(str)) || str2double(str) < 0
            set(src,'String','0');
        elseif str2double(str) > 250
            set(src,'String','250');
        end
        for n = 7:9
            val = get(e_handles(n),'String');
            set(slb_handles(n),'Value',(str2double(val)))
        end
        Adjust_Shape
    end   
       
end
       
  



